<?php
namespace api\controllers;

use common\models\User;
use Yii;
use yii\filters\auth\HttpBasicAuth;
use yii\web\Controller;

class NotificationController extends Controller
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionError($message = 'Not found', $code = 404)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        Yii::$app->getResponse()->setStatusCode($code);
        return $this->asJson(['message' => $message]);
    }

    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => HttpBasicAuth::className(),
                'auth' => function ($username, $password) {
                    $user = User::findByUsername($username);
                    if (!$user) return null;
                    $check = $user->validatePassword($password);
                    return $check? $user: null;
                }
            ]
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'purchase-delete' => ['post'],
//                ],
//            ],
        ];
    }

    public function actionCheckStatus()
    {
        if (Yii::$app->user->identity->status == 10) {
            $status = 10;
            $message = 'Your account is activated';
        }
        else {
            $status = 9;
            $message = 'Your account is not activated';
        }

        return $this->asJson([
            'id' => Yii::$app->user->getId(),
            'status' => $status,
            'message' => $message,
        ]);
    }
}