<?php


namespace api\controllers;


use common\models\User;
use Yii;
use yii\filters\auth\HttpBasicAuth;

class ProfileController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;
    public $enableSession = false;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => HttpBasicAuth::className(),
                'auth' => function ($username, $password) {
                    $user = User::findByUsername($username);
                    if (!$user) return null;
                    $check = $user->validatePassword($password);
                    return $check? $user: null;
                }
            ]
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'purchase-delete' => ['post'],
//                ],
//            ],
        ];
    }

    public function actionInfo()
    {
        return $this->asJson([
            'id' => Yii::$app->user->identity->id,
//            'name' => Yii::$app->user->identity->name,
            'username' => Yii::$app->user->identity->username,
            'email' => Yii::$app->user->identity->email,
            'avatar' => Yii::$app->user->identity->avatar? Yii::$app->user->identity->avatar: '/uploads/site/default_avatar.png',
            'phone' => Yii::$app->user->identity->phone,
//            'push' => Yii::$app->user->identity->push,
            'first_name' => Yii::$app->user->identity->first_name,
            'middle_name' => Yii::$app->user->identity->middle_name,
            'last_name' => Yii::$app->user->identity->last_name,
            'gender' => Yii::$app->user->identity->gender==0 ? 'Male' : 'Female',
            'role' => Yii::$app->user->identity->role==0 ? 'Buyer' : 'Seller',
            'type' => Yii::$app->user->identity->type==0 ? 'Individual' : 'Legal entry',
            'birth_date' => Yii::$app->user->identity->birth_date,
        ]);
    }
}