<?php

namespace api\controllers;

use api\transformers\StoreCategoryList;
use common\models\StoreCategory;

class StoreCategoryController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        $category = null;
        $category = StoreCategory::find()->where(['status' => 1, 'parent_id' => null])->orderBy('order')->all();
        if($category) {
            return $this->asJson(['data' => StoreCategoryList::transform($category)]);
        } else {
            return $this->redirect(['site/error', 'message' => 'Not Found', 'code' => 404]);
        }
    }

    public function actionCategory($id = null)
    {
        $category = null;
        if ($id) {
            $category = StoreCategory::find()->where(['status' => 1, 'id' => $id])->orderBy('order')->all();
        } else {
            $category = StoreCategory::find()->where(['status' => 1, 'parent_id' => null])->orderBy('order')->all();
        }
        if ($category) {
            return $this->asJson(['data' => StoreCategoryList::transform($category)]);
        } else {
            return $this->redirect(['site/error', 'message' => 'Not Found', 'code' => 404]);
        }

    }

}
