<?php

namespace api\controllers;

use common\models\StoreProduct;
use api\transformers\StoreProductList;

class StoreProductController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {

    }

    public function actionShow($id)
    {
        if ($id) {
            $product = StoreProduct::find()->where(['status'=>1, 'id'=>$id])->all();
            return $this->asJson([
                'data' => StoreProductList::transform($product),
            ]);
        } else {
            return $this->redirect(['site/error', 'message' => 'Not Found', 'code' => 404]);
        }
    }

}
