<?php


namespace api\controllers;


use api\transformers\StoreOptionList;
use api\transformers\StoreTypeCarList;
use common\models\StoreOption;
use common\models\StoreType;
use common\models\StoreTypeCar;

class StoreOptionController extends \yii\web\Controller
{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex($id = null)
    {
        $option = null;
        if ($id) {
            $option = StoreOption::find()->where(['status'=>1, 'id' => $id])->orderBy('id')->all();
        } else {
            $option = StoreOption::find()->where(['status'=>1])->orderBy('id')->all();
        }
        if ($option) {
            return $this->asJson(['data' => StoreOptionList::transform($option)]);
        } else {
            return $this->redirect(['site/error', 'message'=> 'Not Found', 'code'=>404]);
        }
    }


}